# baseURL
@baseURL = http://localhost:3000

###
# User Signup
POST {{ baseURL }}/auth/signup
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# User Login
POST {{ baseURL }}/auth/login
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# User Logout
POST {{ baseURL }}/auth/logout
Content-Type: application/json
